### ISSUE TITLE
Text Issue 

### ISSUE THREAD

**Issue by xianga7** [stridera/FierymudMudletClient#1]
Text is not wrapping (starting new line) behind the map/area UI/Box.  It will wrap correctly for the chat/social "box" in upper right hand corner and no text is behind it. 
![image](https://user-images.githubusercontent.com/59627242/71934235-02217000-3172-11ea-81cf-aa869aaa5a8f.png)

**Comment by stridera** [comment]
Need to set a right border   setBorderRight(window width - console percentage)

**Comment by stridera** [comment]
Fixed in latest build
